### ISSUE TITLE
大乱斗发送战绩数据不支持吗？

### ISSUE THREAD

**Issue by Lion-hk** [SnxiaLianXin/LOLAutomationTools#1]
我是大乱斗玩家，已经几个版本了，大乱斗发送战绩数据总是括号里没有数据，能不能修一下啊？
有没有那种玩家综合评分比如说上等马下等马，评分6.2/4.3等等的数据。比如隔壁的joi工具
对于那些不爱配合的玩家，这个提示实力功能真的很让玩家重新评估自己选的英雄和玩法认知。

**Comment by SnxiaLianXin** [comment]
之前更新的时候已经说明过了，你们从来不看更新内容

**Comment by Lion-hk** [comment]
> 之前更新的时候已经说明过了，你们从来不看更新内容

好的好的，其实之前有看到过，但是看到其他功能没有问题，觉得它应该也咩有问题，于是不管它了。
不好意思，非常谢谢。

**Comment by Lion-hk** [comment]
@SnxiaLianXin 已经点击初始化了，还有哪里需要点击的吗。然后试玩了一局发现了bug，数据依旧不正常。
感觉可能是内容太多或者发送太快，不然就是工具没处理好。我开启了对局开启发送敌方战绩，对局开始就是闪烁，聊天框有内容但是不发送。自行快捷键发送也是闪烁。偶尔成功一个两个。
直到后期把内容缩短为名字+评分，才会成功5个，我再测试测试一下看看。
然后提个建议，能否把名字的#数字去掉。因为显示很凌乱，聊天框本身就小，节奏本身紧张而花费时间去看这个会丢失很多注意力。

**Comment by Lion-hk** [comment]
刚测试了两把，选英雄界面可以发队友的，游戏内只能发对面的是吗？游戏里只能发5个内容，而且是简短的名字+评分+20场胜率。
开局依旧闪烁聊天输入框，但是这次没有内容显示在输入框内。

**Comment by Lion-hk** [comment]
发现bug，检测的召唤师ID不正确，游戏里对面id只有3个是对的。

**Comment by SnxiaLianXin** [comment]
游戏内文本发送有很大限制，跟字数没什么关系，跟内容有关系，如果文本里面有被屏蔽的组合词/字（某些人的ID或部分英雄名称）就会导致文本被吞，国服文字狱正常现象。

**Comment by Lion-hk** [comment]
> 游戏内文本发送有很大限制，跟字数没什么关系，跟内容有关系，如果文本里面有被屏蔽的组合词/字（某些人的ID或部分英雄名称）就会导致文本被吞，国服文字狱正常现象。

这个明白，给你我id排查一下把，战争学院<狮子丶是我的宠物>。
然后那个5个id有2个不正确的呢，是否和改名有关系，工具是不是利用数字码查询的。
同时名字后边的数字我觉得去除好些，视觉上很凌乱。

**Comment by SnxiaLianXin** [comment]
> > 游戏内文本发送有很大限制，跟字数没什么关系，跟内容有关系，如果文本里面有被屏蔽的组合词/字（某些人的ID或部分英雄名称）就会导致文本被吞，国服文字狱正常现象。
> 
> 这个明白，给你我id排查一下把，战争学院<狮子丶是我的宠物>。 然后那个5个id有2个不正确的呢，是否和改名有关系，工具是不是利用数字码查询的。 同时名字后边的数字我觉得去除好些，视觉上很凌乱。
> 
> 不对，凌晨有两把开局闪烁发送不了文字，手动可以发送。 其次，屏蔽win键有bug，好几个版本了，运行了一把或者一会后，即便取消，系统一整天都无法使用win键，关闭软件也没有效果。 我是win10，LTSC 2022版本的。

名称不正确可能是用的数据不对（如果有人改名但没重启客户端可能也有这个问题）。发不了文字这个因为系统的文字检测很抽象，有些字句就是发不了，你可以自己去训练营试，如”相同配置机型比新机便宜一半，官方保障，用得放心。“这句话就发不了，但是如果是先发”相同配置机型比新机便宜一半“再发”官方保障，用得放心“就能发。屏蔽LWin键你应该查看是否是因为你按了Fn+LWin锁定了LWin键，如果是这种就会导致无法使用LWin键，目前我尚未发现LWin键屏蔽功能有什么问题。

**Comment by SnxiaLianXin** [comment]
如果要确认是否是因工具设置导致的LWin键无法使用，你应该再检查Ctrl+Esc组合键是否可以正常使用，如果组合键可以正常使用，你就得查看是否是Fn+LWin组合键锁定的问题。
