### ISSUE TITLE
在自定义对局中预亮英雄功能会变成自动ban英雄

### ISSUE THREAD

**Issue by Tudorose** [SnxiaLianXin/LOLAutomationTools#11]
在可以ban英雄的自定义对局中开启了预亮剑圣。结果轮到我ban英雄的时候它自动给我把剑圣ban了。

**Comment by SnxiaLianXin** [comment]
测试了只会选但是不会禁用，不过后续也会调整一下，但是说实话自定义的改不改意义不大。
