### ISSUE TITLE
更新后查询战绩总是出现这种情况。

### ISSUE THREAD

**Issue by Tudorose** [SnxiaLianXin/LOLAutomationTools#15]
更新后，查询战绩的速度虽然变快了一点，但是。非常经常出现查询不到战绩的情况，需要反复刷新战绩。
![image](https://github.com/user-attachments/assets/5976486b-9a2d-493b-99d8-024604b1af7f)

**Comment by SnxiaLianXin** [comment]
这个问题可能有多方面原因造成的，网络、线程调度等等，新版本加了并发数调整设置，你可以自己去更改检索的并发数来尽可能的避免这个问题。
在”战绩查询设置“中下拉找到”对局详情战绩检索并发数“并更改值。
