### ISSUE TITLE
被封号了

### ISSUE THREAD

**Issue by RSRH-Rs** [SnxiaLianXin/LOLAutomationTools#2]
用了两天直接被封号了 有点逆天

**Comment by SnxiaLianXin** [comment]
外服近期在封禁一些Lobby Reveal类的工具（此类工具主要是在排位赛BP阶段中获取队友信息），但是感觉检测的准确度并不高，所以近期不要用那些LCUAPI的工具，可能会导致封号。这件事最抽象的地方就在于数据是用官方给的接口获取的，然后又不让用这些公开的数据，宁愿封禁玩家账号也不去更改数据的获取方式。

**Comment by RSRH-Rs** [comment]
已经申诉了，感觉也没什么用

**Comment by SnxiaLianXin** [comment]
通常第一次因Lobby Reveal类工具导致账号封禁的期限是14天，后续是永久封禁，所以建议是目前外服不要使用LCUAPI的工具，因为封禁的范围比较模糊。

**Comment by RSRH-Rs** [comment]
我是永久封号了我靠 真麻了 还封机器码了

**Comment by Lion-hk** [comment]
你玩的是外服？

**Comment by RSRH-Rs** [comment]
是的 玩的美服
