### ISSUE TITLE
拉黑原因显示不全

### ISSUE THREAD

**Issue by Tudorose** [SnxiaLianXin/LOLAutomationTools#6]
https://github.com/user-attachments/assets/124c8f6f-4861-4ff5-88e2-a2a2743b16b1

拉黑原因无法通过鼠标调整光标位置显示完整的拉黑原因或进行二次编辑，而只能使用左右方向键调整光标位置

**Comment by SnxiaLianXin** [comment]
这个黑名单管理的页面其实一直没完善，后续有空再改进一下。

**Comment by Tudorose** [comment]
有一个额外的问题冒昧想要请教一下，我用笔记本电脑玩撸啊撸，不知道和笔记本电脑有没有关系，反正就是在游戏中Windows键无法使用（ ctrl加ESC键同理），不能使用Windows键切屏，而且该虚拟桌面如果没有额外的窗口（比如选择了在游戏时总是关闭客户端）也不能使用alt加tab键进行切屏，这个和分辨率、是否打开了游戏模式、还有全屏、窗口化、无边框、快捷键冲突等等都没有关系，请问这个问题我有没有可能找到解决办法？

**Comment by SnxiaLianXin** [comment]
> 有一个额外的问题冒昧想要请教一下，我用笔记本电脑玩撸啊撸，不知道和笔记本电脑有没有关系，反正就是在游戏中Windows键无法使用（ ctrl加ESC键同理），不能使用Windows键切屏，而且该虚拟桌面如果没有额外的窗口（比如选择了在游戏时总是关闭客户端）也不能使用alt加tab键进行切屏，这个和分辨率、是否打开了游戏模式、还有全屏、窗口化、无边框、快捷键冲突等等都没有关系，请问这个问题我有没有可能找到解决办法？

你游戏中按到Ins键或者自己开了功能键屏蔽的设置。

**Comment by Tudorose** [comment]
![image](https://github.com/user-attachments/assets/aca28244-3bff-47a9-853f-372cdfeaed8b)
希望可以在对局详情这个界面中查看已经拉黑的玩家时，可以复制拉黑原因。把它弄成文本模式，可以选择复制或者直接一键复制，或者发送战绩的时候，可以连带着发送都可以。这样我想要复制他的拉黑原因发送到聊天框中时，就不需要打开黑名单列表，复制他的ID进去搜索，然后再复制。谢谢大佬。

**Comment by Tudorose** [comment]
> ![image](https://private-user-images.githubusercontent.com/55563679/371473622-aca28244-3bff-47a9-853f-372cdfeaed8b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc0NDc4NjMsIm5iZiI6MTcyNzQ0NzU2MywicGF0aCI6Ii81NTU2MzY3OS8zNzE0NzM2MjItYWNhMjgyNDQtM2JmZi00N2E5LTg1M2YtMzcyY2RmZWFlZDhiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI3VDE0MzI0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIzZGViMjcyMGJiZDQ3YzJlYWEwMTE1YWQzNDc2M2UzZjIzZTU3YjZkYTVjZDE5YzRhNzJlMzE4ZDI4MGQ3NjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.rq2iOSqxjz7_fU9xIV7gCh2_xGqDd9WvBZmePoZF1sk) 希望可以在对局详情这个界面中查看已经拉黑的玩家时，可以复制拉黑原因。把它弄成文本模式，可以选择复制或者直接一键复制，或者发送战绩的时候，可以连带着发送都可以。这样我想要复制他的拉黑原因发送到聊天框中时，就不需要打开黑名单列表，复制他的ID进去搜索，然后再复制。谢谢大佬。

举个例子，LOL079在进入BP时也会在聊天框提示有黑名单成员，同时提示拉黑原因，可以直接复制粘贴发送
