### ISSUE TITLE
9月18日版本无法开启

### ISSUE THREAD

**Issue by Lion-hk** [SnxiaLianXin/LOLAutomationTools#8]
刚更新
我操作的步骤是：检测到更新后自动打开了网页，然后旧版本上点击了还原，接着下载好了就把旧版关闭并把新版替换进文件夹。
现在一直无法打开，每次一开启读在同意界面，尝试在文档文件夹里把DATA删了也开不了。

**Comment by Lion-hk** [comment]
[Log_2024-9-20.Json](https://github.com/user-attachments/files/17063671/Log_2024-9-20.Json)
这是日志

**Comment by Lion-hk** [comment]
[Log_2024-9-19.Json](https://github.com/user-attachments/files/17064195/Log_2024-9-19.Json)
还是打不开

**Comment by SnxiaLianXin** [comment]
> [Log_2024-9-19.Json](https://github.com/user-attachments/files/17064195/Log_2024-9-19.Json)
> 还是打不开

可以自己手动到  文档-LOLAutomationTools-DATA-Config文件夹下面创建一个Config.json文件，可以跳过这个窗口如果已经有配置文件还是显示这个窗口只能等我晚上回去再解决了
