### ISSUE TITLE
自动选派功能异常

### ISSUE THREAD

**Issue by Tudorose** [SnxiaLianXin/LOLAutomationTools#9]
![IMG_20240923_223626](https://github.com/user-attachments/assets/666a8c91-32fb-4d6d-97ff-3d9f48635f75)

**Comment by SnxiaLianXin** [comment]
什么CPU啊？

**Comment by Tudorose** [comment]
> 什么CPU啊？

amd4800amd4800hh

**Comment by Tudorose** [comment]
> 什么CPU啊？

解决了，用了以前的pickcards.json

**Comment by SnxiaLianXin** [comment]
> > 什么CPU啊？
> 
> 解决了，用了以前的pickcards.json 

那新的PickCards.json你应该把配置里面的Detect的Mode项改为Compare或者Exact，都试一下看哪个能用

**Comment by SnxiaLianXin** [comment]
> > 什么CPU啊？
> 
> 解决了，用了以前的pickcards.json

那新的PickCards.json你应该把配置里面的Detect的Mode项改为Similar或者Exact，都试一下看哪个能用

**Comment by Tudorose** [comment]
更新之后还有 一个问题， 用快捷键调出对局详情点击黑名单填写拉黑原因的窗口无法保持在撸啊撸上方，必须切出英雄联盟进行填写，记得以前都可以直接在英雄联盟窗口的上方可以直接填写

**Comment by Tudorose** [comment]
更换电脑后，2560*1600分辨率下出现算术运算导致溢出，使用以前版本的JSON文件不能解决问题。

**Comment by Seraph1ne** [comment]
> 更换电脑后，2560*1600分辨率下出现算术运算导致溢出，使用以前版本的JSON文件不能解决问题。

https://m.bilibili.com/video/BV1dii6YTEbv

**Comment by Tudorose** [comment]
你这样把这个功能的视频发到b站上，恐怕有风险😅

AzhC
________________________________
